import { ReactElement, ReactNode } from 'react';
import GlobalHeader from '@/components/GlobalHeader';
import Head from 'next/head';
import { NextPage } from 'next';
import { ThemeContextProvider } from '@/context/ThemeContext';
import { AuthContextProvider } from '@/context/AuthContext';
import { Container } from '@mui/material';
import { Provider } from 'react-redux';
import { store } from '@/store/store';
import type { AppProps } from 'next/app';
import '@/styles/globals.css';

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);

  return getLayout(
    <Provider store={store}>
      <AuthContextProvider>
        <ThemeContextProvider>
          <Container>
            <Head>
              <title>Pet Sanctuary</title>
              <meta name='description' content='Generated by create next app' />
              <meta name='viewport' content='width=device-width, initial-scale=1' />
              <link rel='icon' href='/favicon.ico' />
            </Head>
            <GlobalHeader />
            <Component {...pageProps} />
          </Container>
        </ThemeContextProvider>
      </AuthContextProvider>
    </Provider>
  );
}
