import { ReactNode } from 'react';
import Head from 'next/head';
import HeroSection from '../components/HeroSection';
import Categories from '../components/Categories';
import { Container, Stack } from '@mui/material';
import Layout from '@/components/Layout';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <main>
          <Container sx={{ pb: 4 }}>
            <Stack spacing={4}>
              <HeroSection />
              <Categories />
            </Stack>
          </Container>
        </main>
        <footer></footer>
      </div>
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactNode) {
  return <Layout>{page}</Layout>;
};

export default HomePage;
