import Head from "next/head";
import GlobalHeader from "./GlobalHeader";
import { Container } from "@mui/material";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div>
          <header>
            <Container>
              <GlobalHeader />
            </Container>
          </header>
          <main>
            {children}
          </main>
          <footer></footer>
        </div>
      </>
  );
}
